image: maven:3.3.9-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
  - .m2/repository/
  - target/

build:
  stage: build
  script:
  - mvn $MAVEN_CLI_OPTS clean install -B

test:
  stage: test
  script:
  - mvn $MAVEN_CLI_OPTS test -B

